### ISSUE TITLE
[PE-D][Tester C] NRIC could be inserted as upper case

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-3/tp#246] opened 2024-11-08 20:50 UTC
![image.png](https://raw.githubusercontent.com/ghos7ie/ped/main/files/cccd251e-b624-45c1-bef6-99ef0207b2d5.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ghos7ie/ped#13

**Comment by Zenkoh1** [comment] 2024-11-08 20:55
Duplicate of #204

**Closed by Zenkoh1** 2024-11-08 20:55 UTC
